// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4534.InfiniteRecharge2020.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4534.InfiniteRecharge2020.Robot;
import java.math.*;

/**
 *
 */
public class GoToCone extends Command {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    double angle = 0;
    double size = 0;
    boolean followOffscreen;
    double lastKnownPosition;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public GoToCone(boolean followOffscreenT) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        followOffscreen = followOffscreenT;
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
       
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        angle = Robot.limelight.getXSkew();
        size = Robot.limelight.getYellowBoxHorizontal();
        float speed = 0;
        float rotation = 0;
        if (angle > 1) {
            rotation = (float)(angle/22.5 * 0.5 + 0.5);
        }
        else if (angle < -1) {
            rotation = (float)(angle/22.5 * 0.5 - 0.5);
        }
        if (size < 120) {
            speed = (float)0.6;
        }
        Robot.driveTrain.ArcadeDrive(speed, rotation);
        if(lastKnownPosition < -15 && !Robot.limelight.limelightHasTarget()) Robot.driveTrain.ArcadeDrive(0, -0.5);
        if(lastKnownPosition < 15 && !Robot.limelight.limelightHasTarget()) Robot.driveTrain.ArcadeDrive(0, 0.5);
        lastKnownPosition = angle;
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return size > 120;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        Robot.driveTrain.TankDrive(0,0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
        Robot.driveTrain.TankDrive(0,0);
    }
}
